name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Upload Jest test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jest-results
        path: jest-results.xml

    - name: Upload Jest HTML report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jest-html-report
        path: .html-report/report.html